### ISSUE TITLE
Calculate TVL amount

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#140]
1. Read [guidelines](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5).
2. We're fetching amount for all opened position [here](https://github.com/djeck1432/spotnet/blob/main/web_app/db/crud.py#L365) but we sum all position together despite on the token for each position, however, there could be different tokens, like: `ETH`, `STRK`, `USDC`.
3. Fetch current prices using this method [get_current_prices](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/mixins/dashboard.py#L31)
4. Map current prices and amount for each token position and then return in this method[get_stats](https://github.com/djeck1432/spotnet/blob/main/web_app/api/user.py#L138) sum of all assets based on current price:
p.s. so if you have in db `ETH`: 100, `STRK`: 20, `USDC`: 100, you should convert `ETH` and `STRK` to `USDC` current price and multiply on the amount of these tokens appropriate and return total amount of all assets in `USDC`

**Comment by mimisavage** [comment]
Can I work on this ?

**Comment by josephchimebuka** [comment]
Could I be assigned to this?

**Comment by mimisavage** [comment]
I want to take on this issue, can I be assigned?

**Comment by Yunusabdul38** [comment]
I’d like to resolve this.

**Comment by anonfedora** [comment]
hi, i'm a fullstack blockchain developer, and i can handle the issue efficiently. ETA: 8hours

**Comment by mimisavage** [comment]
I want to take on this issue, can I be assigned?

**Comment by aniruddhaaps** [comment]
I'm a python dev, a new-comer here. I want to take up the issue and solve it.

**Comment by mimisavage** [comment]
I want to take on this issue, can I be assigned?

**Comment by mimisavage** [comment]
Would love to tackle this

**Comment by 0xdevcollins** [comment]
May I handle this issue?

**Comment by caxtonacollins** [comment]
Is it okay if I take this? I like 🍒 and am ready to work..... please assign me

**Comment by mimisavage** [comment]
Will resolve this by trying to retrieve all opened positions from the database, regardless of token type (ETH, STRK, USDC, etc.).
Get current prices
Using the get_current_prices method, I'll fetch the current prices for each token.
Map prices to positions
Will then create a dictionary mapping each token to its current price 
Convert tokens to USDC
For each position, I'll convert the token amount to USDC using the current price.
Calculate total assets
I'll sum up the USDC-converted amounts for all positions.
Return total stats
In the get_stats method, 'll return the total sum of all assets in USDC.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js, TypeScript, and Python. I’ve made over 31 contributions to over 12 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I will tackle this task by enhancing the stats endpoint by implementing accurate TVL  calculation that properly handles multiple token types. 
The current implementation incorrectly sums different token amounts without price conversion. I will modify the `PositionDBConnector` to group opened positions by token symbol, fetch current prices using the existing `get_current_prices()` method, convert each token position to its "USDC" equivalent, and aggregate all values for total TVL in "USDC". For example, if we have "100 ETH at $3000/ETH, 20 STRK at $50/STRK", and 100 "USDC", the system will correctly report TVL as "301,100 USDC "rather than just summing raw amounts. The implementation will include error handling, logging, and use Decimal type for precision. ETA 24 hours from task assignment. I like 🍇.

**Comment by djeck1432** [comment]
@suhas-sensei  1. November, it won't work, if you can do it till during 24 hours, it's okay

**Comment by suhas-sensei** [comment]
@djeck1432 maybe i can try in 24hours, ill reschedule some of my work for later
