### ISSUE TITLE
[Backend] Disable connect wallet if user doesn't have CRM token

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#207]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Disable on frontend connecting to wallet, if user doesn't have `CRM` token
CRM address = `0x051c4b1fe3bf6774b87ad0b15ef5d1472759076e42944fff9b9f641ff13e5bbe`
3. Share with your wallet id for Starknet in telegram via DM I will send you some tokens for testing
4. If user doesn't have please pop up window, that beta testing allows only for user who has `CRM` token
5. Disable this checking if we run `dev` container for local development using env variable
6. Update `.env.example` file 
7. Update README file with this field

**Comment by Villarley** [comment]
Hi @djeck1432 ,

I’m a Dojo Coding member and an active contributor to the OSS community. I’ve worked on several Web3 projects, including contributions to stellar projects, specifically building on StarkNet. I also have solid experience with React, and as a Web3 hackathon buildathon winner.

I would like to contribute to this issue because I want to start contributing to spotnet, and as I see is labeled for new contributors. I like 🍎🍎

**Comment by KevinLatino** [comment]
hi
