### ISSUE TITLE
[Backend] Fix test cases part 2

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#335]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Write approximately time for distributing this task when you applying.
3. Fix all failed test cases:
4. Set up project and run `pytest web_app/tests`
5.  Fix test cases for next files:
- `test_deposit_mixin.py`

**Comment by mymiracle0118** [comment]
Can I jump on this task?

**Comment by ekumamatthew** [comment]
Can I start working on this? I like cherry.

**Comment by GideonBature** [comment]
I’d like to help with this.

**Comment by morelucks** [comment]
Hi, I'm Kamshak Lucky Isuwa.
A developer with experience in Python and backend development, particularly in writing and testing APIs, optimizing codebases, and debugging complex issues. My stack includes Python, Django, solidity, cairo. I also have experience with StarkNet and blockchain-based projects, making me familiar with the tools and technologies referenced 
in this task.

## Set Up the Project

Fork the repository and create a new branch using the format feat/fix-test-cases.
Follow the README.md to set up the project environment locally and ensure dependencies are properly installed.
## Identify Failing Test Cases

Run pytest web_app/tests to isolate and analyze issues in:
test_deposit_mixin.py
test_starknet_client.py.
Use log outputs and debugging techniques to identify the root cause of failures.
## Fix Test Cases

Address any logic errors, missing mocks, or misconfigurations in the test setup.
Ensure compatibility and proper mocking for dependencies (especially StarkNet clients).

**Comment by djeck1432** [comment]
@GideonBature Sorry, you were unassigned due to missing draft PR within 12 hours and didn't get any message from you

**Comment by 1nonlypiece** [comment]
Hi @djeck1432, can you please give me a chance to work on this issue? I like cherry

**Comment by GideonBature** [comment]
> @GideonBature Sorry, you were unassigned due to missing draft PR within 12 hours and didn't get any message from you

was already working on the fix, and have started fixing them. Just wanted to finish before requesting for PR. But no problem, let me turn down my docker then. Thank you!

**Comment by djeck1432** [comment]
@GideonBature did you read guideline?

**Comment by GideonBature** [comment]
> @GideonBature did you read guideline?

I did. Had problem setting up environment earlier on first(which I communicated on the TG group), which I later resolved it before I started(deleted the message from TG after I was able to resolve that part), was hoping to fix the tests before end of the day before requesting for a PR. 

Will take note and adhere strictly to the guideline next time.

**Comment by 1nonlypiece** [comment]
Hi @djeck1432, This test failure does not seem straightforward. Should I get some additional time to fix it, as I'm new to this codebase?

**Comment by djeck1432** [comment]
@1nonlypiece yeah for sure, but please wait one hour, I will merge a lot of changes so most probably you will have a bit different result in these test cases.

**Comment by djeck1432** [comment]
@1nonlypiece I merged to `main` branch, so you can sync, But if you can't manage relatively fast, I don't think it will work out, because we will push till end of the week a lot of changes, so your code would be broken every day. 
maybe you wanna try something easier?

**Comment by 1nonlypiece** [comment]
@djeck1432 yes, it will be good if i start with easier one.

**Comment by emarc99** [comment]
Can I take this issue? Seems quite straight forward.
I like cherry.

**Comment by emarc99** [comment]
Can I take this issue? Seems quite straight forward.
I like cherry.

**Comment by djeck1432** [comment]
@emarc99 any updates?
