### ISSUE TITLE
[Documentation] Create documentation for pages

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#412]
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Add documentation for Zklend
3. Defi Spring
4. Spotnet overview

**Comment by Kostya-59benz** [comment]
I have experience about this task, I like strawberry

**Comment by nottherealalanturing** [comment]
I already have the project setup and could work on this, I like strawberries  TG@assadeesaa

**Comment by BigBen-7** [comment]
I like strawberry.
TG:@BigBen1909
My Approach:
For documenting ZkLend, DeFi Spring, and Spotnet Overview, I’ll start by defining the scope, gathering details, and organizing the content into clear, modular sections. I’ll write concisely, add visuals where needed, and ensure accuracy through reviews.

**Comment by yusuftomilola** [comment]
I am a new contributor. Very resourceful. I have read the guidelines and i am ready to work on the issue. I will give timely updates and progress reports as the issue is been resolved. I like strawberry. 

Telegram handle - @tomilolaaaaa

Method of Approach - Research and understand what the structure and get as much information as possible. Write out a clear documentation and ensure accuracy by cross-checking with official sources or existing materials.

**Comment by PavelShkurko** [comment]
hi. I like strawberry , may I tackle this issue
