### ISSUE TITLE
Create test cases for dashboard

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#75]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. Add test cases for next positive and negative scenarios for next endpoint [here](https://github.com/djeck1432/spotnet/blob/main/web_app/api/dashboard.py#L15):
- `get_dashboard`
4. Add test cases for [`DashboardMixin`](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/mixins/dashboard.py#L13)
- `get_wallet_balances`
- `get_zklend_position`
- `_get_products`

**Comment by Mystic-Nayy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a web3 developer

### How I plan on tackling this issue
I will 
1. Add tests for get_wallet_balances to check correct balance retrieval and handle edge cases.
2. Test get_zklend_position for accurate position retrieval, including nonexistent accounts.
3. Verify _get_products returns the correct product list and handles cases with no products or invalid input.

**Comment by djeck1432** [comment]
@Mystic-Nayy please, read first guidline https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a Full Stack Developer with experience in blockchain and testing. I am skilled in writing Javascript, Rust, Cairo and python.  I've made  over 18 contributions  in the OnlyDust ecosystem, delivering solid solutions quickly. 

### How I plan on tackling this issue
I will then write test cases for the `get_dashboard` endpoint, covering both positive and negative scenarios to make sure it works well. I will also add tests for the DashboardMixin methods: `get_wallet_balances`, `get_zklend_positionardMixin` methods: `get_wallet_balances`, `get_zklend_positionardMixin methods: `get_wallet_balances`, `get_zklend_position`, and `_get_products`, ensuring all cases are tested. The code will be clear, documented, and meet all the project requirements. I like orange.

**Comment by jaykayudo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a First Principle Engineer, Python developer and software engineer with ample experience in building software application , python application and web3 applications. I like Orange.

### How I plan on tackling this issue
- I will create the testcases for get_dashboard route using pytest. 
- I will convert the asynchronous operation to synchorous operation in order to test with synchronous testcases
- I will test the `get_wallet_balances` classmethod to check that the balance is gotten properly and to check that no balance is added to the wallet for failed get operations.
- I will test the `get_zklend_position` for accurate position retrieval
- I will test the `_get_products` method to get products from the dapps and in this case, i will create mocks  for the testing

**Comment by Mystic-Nayy** [comment]
> @Mystic-Nayy please, read first guidline https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5

I have sir

**Comment by djeck1432** [comment]
@Mystic-Nayy, sorry, you didn't do on time draft PR, I will unassign you for this task

**Comment by Mystic-Nayy** [comment]
@djeck1432 Sorry i missed that i had a little technical issue but i am stable now and i have started, Can i still go on?

**Comment by djeck1432** [comment]
@Mystic-Nayy Nope, sorry, next time, you had more than enough time to create at least draft PR, in case you have technical issue, you should have texted in telegram. Text me in DM, will see if you can take new task.

@0xdevcollins feel free to start working on it

**Comment by 0xdevcollins** [comment]
Okay 👌 thank you ☺️
