### ISSUE TITLE
Create endpoint for fetching mulitpier per token

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#77]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. In [position.py](https://github.com/djeck1432/spotnet/blob/main/web_app/api/position.py) create new endpoint: `get_mulitpiers` which will return data like `{"ETH": <multilpier>}`
4. Create `dataclass` which is called `TokenMultipliers` in [constants.py](https://github.com/djeck1432/spotnet/blob/main/web_app/contract_tools/constants.py) with next values:
```
 ETH = 5
 STRK = 2.5
 USDC = 5
```
5. Add serializer response model for new created endpoint, `TokenMulitpliersResponse` in [posotion.py](https://github.com/djeck1432/spotnet/blob/main/web_app/api/serializers/position.py)

**Comment by Josh-121** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
Software engineering background majored in backend & Smart contract development 

### How I plan on tackling this issue
I would :
Define the endpoint route as /api/multipliers.

Implement logic to return multipliers for tokens in JSON format.

Create a data class named TokenMultipliers with the following attributes:

ETH = 5

STRK = 2.5

USDC = 5

3. Create Serializer Response Model in position.py

Define a response model called TokenMultipliersResponse to structure the response for the multipliers.

4. Implement Logic in get_multipliers

Use the TokenMultipliers data class to fetch the multipliers.

Return the data in the structure defined by TokenMultipliersResponse.
5. Work on feedback/recommendations & I like orange

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a Full Stack Developer with experience in maintaining and upgrading codebases to align with the latest standards. I am skilled with writing Cairo, Rust, Javascript and Python. I’ve successfully worked on over 12 projects in the OnlyDust ecosystem, ensuring smooth transitions during updates.

### How I plan on tackling this issue
In order to tackle this task, I will start by setting  up the project  following the `README.md`. In `position.py`, I will create a new endpoint, `get_multipliers`, which will return data in the format `{"ETH": <multiplier>}`. I will define a TokenMultipliers dataclass in `constants.py` with the given values for `ETH, STRK, and USDC`. I will also create a serializer response model, `TokenMultipliersResponse`, in `position.py` for the new endpoint. I like orange.

**Comment by jaykayudo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a First Principle Engineer, Python developer and software engineer with ample experience in building software application , python application and web3 applications. 

### How I plan on tackling this issue
- I will create a new endpoint `get_multiplier` to get the multiplier of the token symbol that is passed from the request and return it as a json response in the format of `{"ETH": <multilpier>}`.
- I will create a serializer dataclass to hold the value of the multiplier in the constants.py file.
- I will manually test to ensure that right reponse is returned for the right request
- I will  write testcases if required for the endpoint that i created
I like Orange.

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
starknet foundry- #2581

Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and python, and Cairo.

### How I plan on tackling this issue
To solve this sissue, I'll take the following steps:
1.I'll create new endpoint route as /api/multipliers get_multipliers, which will return data in the format {"ETH": <multiplier>}
2.I will define a TokenMultipliers dataclass in constants.py with the given values for ETH, STRK, and USDC
3. I will create a serializer response model, TokenMultipliersResponse, in position.py for the new endpoint

I like orange
