### ISSUE TITLE
Add test cases for `positions` endpoints

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#78]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Set up the project, read [README.md](https://github.com/djeck1432/spotnet/blob/main/README.md#development-environment-setup) how to do that.
3. Create test cases (positive and negative scenarios) for positions endpoints which you can find [here](https://github.com/djeck1432/spotnet/blob/main/web_app/api/position.py)
P.s. Database connection has been already mocked, so you don't need to take care of it.

**Comment by Mystic-Nayy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a web3 developer

### How I plan on tackling this issue
I will write positive tests for successful scenarios (e.g., valid "GET" or "POST /positions").  
Write negative tests for invalid inputs, checking for proper error handling.  
Use mock data and run the tests to ensure all cases are covered correctly.

**Comment by djeck1432** [comment]
@Mystic-Nayy Please, read first guidline https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5

**Comment by jaykayudo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a First Principle Engineer, Python developer and software engineer with ample experience in building software application , python application and web3 applications. I like Orange.

### How I plan on tackling this issue
- I will create the testcases for all position endpoint and test the negative and positive effect and cover as much scenerios as possible

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a Full Stack Developer with experience in maintaining and upgrading codebases to align with the latest standards. I am skilled with writing Cairo, Rust, Javascript and Python. I’ve successfully worked on over 12 projects in the OnlyDust ecosystem, ensuring smooth transitions during updates.

### How I plan on tackling this issue
To tackle this task, I will set up the project by following the instructions in the `README.md`. I will then create test cases for the positions endpoints, covering both positive and negative scenarios. Since the database connection is already mocked, I will focus on testing the functionality of the endpoints to ensure they work correctly in all cases. I like orange.

**Comment by djeck1432** [comment]
Sorry, this issue is duplicated
