### ISSUE TITLE
Add test cases for FE utils

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#91]
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Create `test` folder in [frontend](https://github.com/djeck1432/spotnet/tree/main/frontend) directory 
3. Add test cases (positive and negative) for next files:
- [contract.js](https://github.com/djeck1432/spotnet/blob/main/frontend/src/utils/contract.js)
-  [transaction.js](https://github.com/djeck1432/spotnet/blob/main/frontend/src/utils/transaction.js)
- [wallet.js](https://github.com/djeck1432/spotnet/blob/main/frontend/src/utils/wallet.js)
4. Update [README.md](https://github.com/djeck1432/spotnet/blob/main/frontend/README.md) how to run the test cases

**Comment by djeck1432** [comment]
> I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).
> 
> ### My background and how it can be leveraged
> i am a python dev and willing to contribute

It's for Frontend not Backend

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
I am a python dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

### How I plan on tackling this issue
I would approach this issue by

 1. Test folder creation in frontend directory  contains Jest and then make Positive/Negative test cases on contract.js, transaction.js, and wallet.js files.

2. Update README.md to mention how to run the tests using npm test.

**Comment by BrunoAmbricca** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
Hello guys, I have been working for the past 4 year in developing with js, ts, java and been working in big companies that request a huge test coverage for the code.

### How I plan on tackling this issue
I would look the files that need tests and understand all the cases to test, the start doing unit tests for all the cases also covering all the border cases that I find and you guys found during the development

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spotnet).

### My background and how it can be leveraged
Hello, I'm Dprof-in-tech, a seasoned Full Stack Blockchain Developer, and I'm excited to be part of ODHACK 9! I have a strong foundation in technologies such as Next.js, TypeScript, JavaScript, React, Node.js, Rust, and Cairo, I've built extensive experience across the blockchain development landscape.

I first got involved with OnlyDust during Edition 2, and since then, I've made 39 contributions across 11 different projects. Working on the platform has really helped me sharpen my skills, especially when it comes to delivering great solutions under tight deadlines. I love combining technical know-how with a user-focused approach, whether it's building immersive 3D experiences or crafting smart contracts that solve real-world problems.

Throughout, I've consistently demonstrated the ability to adapt and contribute effectively to diverse challenges. I'm confident in my ability to tackle new problems and drive innovation within the blockchain space. As we kick off ODHACK 9, I'm eager to apply my previous experience and technical expertise to push the boundaries of what's possible.

You can view my public profile on OnlyDust here: https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
Here's my approach to implementing frontend test cases for the functions in the mentioned files.:

Test Environment Setup:
I'll set up Jest / Vitest environment with the proper testing packages.
Add custom matching parameters for blockchain-specific assertions.
Configure Web3 mocking utilities and use environmental images.

Contract Tests Coverage:
I will write tests to cover  for contract initialization and all other parts of the intended functions.

Transaction Tests Coverage:
I will write full coverage tests with enough edge cases for both the transaction and wallets functions.

Update README:
I would update the readme to reflect how to run these tests.

Timeline: 1-2 days from the day of assignment.


I would love to contribute to this project and yes, i like orange
